name: coil_example
description: A sample command-line application.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
   coil:
     path: ../coil

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
